-- ============================================================================
-- 0003_storage.sql
-- Storage buckets + access policies.
--
-- We use a single private bucket `ugc-assets`. Paths are namespaced:
--   models/{userId}/{modelId}/{filename}
--   products/{userId}/{productId}/{filename}
--   generated/{userId}/{projectId}/{generationRequestId}/{filename}
--   revisions/{userId}/{projectId}/{revisionRequestId}/{filename}
--
-- Clients never touch storage directly. The server signs URLs and uploads
-- generated bytes using the service-role key. We still keep RLS-style policies
-- in place as a defense-in-depth measure for any direct-from-client uploads.
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('ugc-assets', 'ugc-assets', false)
on conflict (id) do nothing;

-- A user can read/write objects whose path starts with one of the four roots
-- AND whose second path segment matches their auth.uid().
-- The path layout above guarantees the user's id is always the second segment.

drop policy if exists "ugc_assets_owner_read" on storage.objects;
create policy "ugc_assets_owner_read"
  on storage.objects for select
  using (
    bucket_id = 'ugc-assets'
    and auth.uid()::text = (storage.foldername(name))[2]
    and (storage.foldername(name))[1] in ('models','products','generated','revisions')
  );

drop policy if exists "ugc_assets_owner_insert" on storage.objects;
create policy "ugc_assets_owner_insert"
  on storage.objects for insert
  with check (
    bucket_id = 'ugc-assets'
    and auth.uid()::text = (storage.foldername(name))[2]
    and (storage.foldername(name))[1] in ('models','products','generated','revisions')
  );

drop policy if exists "ugc_assets_owner_update" on storage.objects;
create policy "ugc_assets_owner_update"
  on storage.objects for update
  using (
    bucket_id = 'ugc-assets'
    and auth.uid()::text = (storage.foldername(name))[2]
  );

drop policy if exists "ugc_assets_owner_delete" on storage.objects;
create policy "ugc_assets_owner_delete"
  on storage.objects for delete
  using (
    bucket_id = 'ugc-assets'
    and auth.uid()::text = (storage.foldername(name))[2]
  );
