import "server-only";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { serverEnv } from "@/lib/env";

let cached: SupabaseClient | null = null;

// Service-role client. Bypasses RLS. Only use after the caller has been
// authenticated separately. We use this to upload generated bytes to storage
// (which the user can't do directly because the bytes live on the server).
export function getSupabaseServiceClient(): SupabaseClient {
  if (cached) return cached;
  const env = serverEnv();
  cached = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });
  return cached;
}
